//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDF.JK.WebAdmin.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Education { get; set; }
        public string NativePlace { get; set; }
        public string Nation { get; set; }
        public string Identification { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Avocation { get; set; }
        public string Phone { get; set; }
        public string Marital { get; set; }
        public string Interest { get; set; }
        public string LearningExperience { get; set; }
        public string workExperience { get; set; }
        public string SelfEvaluation { get; set; }
        public string ImgSrc { get; set; }
    }
}
